name: Playwright C# Tests

on:
  workflow_dispatch:
    inputs:
      run_username:
        description: "SauceDemo username (optional; overrides secret)"
        required: false
      run_password:
        description: "SauceDemo password (optional; overrides secret)"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore
        working-directory: DemoProject

      - name: Install Playwright Browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps
        working-directory: DemoProject

      - name: Set credentials (inputs override secrets)
        run: |
          echo "SAUCE_USERNAME=${{ github.event.inputs.run_username != '' && github.event.inputs.run_username || secrets.SAUCE_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_PASSWORD=${{ github.event.inputs.run_password != '' && github.event.inputs.run_password || secrets.SAUCE_PASSWORD }}" >> $GITHUB_ENV

      - name: Run tests (headless in CI)
        env:
          SAUCE_USERNAME: ${{ env.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ env.SAUCE_PASSWORD }}
          CI: "true"
        run: dotnet test --logger "trx;LogFileName=test_results.trx"
        working-directory: DemoProject

      - name: Upload TestResults
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: |
            DemoProject/TestResults/**/*.png
            DemoProject/**/TestResults/**/*.png
            DemoProject/**/*.trx
          if-no-files-found: ignore
